db:
  host: 'localhost'
  port: 5432
  username: 'developer'
  password: 'dbonfire'
  database: 'telegram'
  synchronize: true
  dropSchema: false
  logging: true

jwt:
  # TODO
  secret: 'change-it-to-something-secure'
  expiresIn: '7d'

aws:
  S3_BUCKET_PIC: 'tg-dev-pic'
  S3_BUCKET_ID: 'tg-dev-id'
  S3_BUCKET_BIO: 'tg-dev-bio'
  S3_BUCKET_REPORT: 'tg-dev-report'
  S3_REGION: 'ap-south-1'
